name: Prepare iOS
description: Prepare iOS environment

runs:
  using: composite
  env:
    BUNDLE_GEMFILE: ${{ github.workspace }}/TestApp/Gemfile
  steps:
    - name: Cache Pods
      uses: actions/cache@v4
      with:
        path: |
          ios/Pods
          TestApp/ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
