name: Native Tests & Apps

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      # setup JDK environment
      - name: Set up our JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Finalize Android SDK
        run: |
          /bin/bash -c "yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null"

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Unit Tests for Android
        run: yarn test:android

      - name: Bundle TestApp JS for Android
        run: mkdir TestApp/android/app/src/main/assets && (cd TestApp;yarn bundle:android)

      - name: Build TestApp for Android
        run: |
          yarn run build:android

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Cache Lib cocoapods
        id: cocoapods-cache-lib
        uses: actions/cache@v3
        with:
          path: |
            ios/Pods
            TestApp/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-cocoapods-

      - name: Install Lib cocoapods
        run: |
          (cd ios;pod install)

      - name: Run Unit Tests for iOS
        run: yarn test:ios

      - name: Install TestApp cocoapods
        run: |
          (cd TestApp/ios;pod install)

      - name: Bundle TestApp JS for iOS
        run: (cd TestApp;yarn bundle:ios)

      - name: Build TestApp for iOS
        run: |
          yarn run build:ios
