name: Native Tests & Apps

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-native-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Prepare Android
        uses: ./.github/actions/prepare-android

      - name: Run Unit Tests for Android
        run: yarn test:android
  build-testapp-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Prepare Android
        uses: ./.github/actions/prepare-android

      - name: Bundle TestApp JS for Android
        run: mkdir TestApp/android/app/src/main/assets && (cd TestApp;yarn bundle:android)

      - name: Build TestApp for Android
        run: |
          yarn run build:android

  test-native-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Prepare iOS
        uses: ./.github/actions/prepare-ios

      - name: Install Lib cocoapods
        run: |
          (cd ios;pod install)

      - name: Run Unit Tests for iOS
        run: yarn test:ios
  build-testapp-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Prepare iOS
        uses: ./.github/actions/prepare-ios

      - name: Install TestApp cocoapods
        run: |
          (cd TestApp/ios;pod install)

      - name: Bundle TestApp JS for iOS
        run: (cd TestApp;yarn bundle:ios)

      - name: Build TestApp for iOS
        run: |
          yarn run build:ios
